// <auto-generated />
using System;
using ApiSchool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSchool.Migrations
{
    [DbContext(typeof(Data_SystemDbContext))]
    [Migration("20230321133953_IntegrationDataSystem")]
    partial class IntegrationDataSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiSchool.Models.LogExceptionModel", b =>
                {
                    b.Property<int>("LogExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.HasKey("LogExceptionId");

                    b.ToTable("LogException");
                });
#pragma warning restore 612, 618
        }
    }
}
